### PR TITLE
Extracted movie data from the past 10 years (2010-2020)

### PR DESCRIPTION
**Pull request by NivesKrizanec**

### CODE REVIEW

**Comment by mboehm7** [comment]
Great, thanks for the initial extracted data set @NivesKrizanec - couple of comments:

* Please, add a markdown readme file with example records of the three files so students get a gist without downloading the entire file. This should also include the reference to the source of the files because we need to give the dataset creators credit (and at least one of the licenses requires it). You'll find examples in the other datasets of this repo.
* Try to create consistency across all references of countries (e.g., en vs en-English vs FR-France vs tl-)
* Drop the crew attribute from Movies.csv (please also rename from MovieMetadata) and related persons from Persons.csv. I think the scenario is already complex enough and the characteristics of crew handling are almost identical to cast handling.
* Rename the attribute CastCreditID to CastIDs
* Avoid the nead for double quoting as a means of escaping strings which contains commas. You can maybe replace these commas with a semicolon (e.g., "France 2 Cinéma|Quinta Communications|Carthago Films S.a.r.l.|Prima TV|Doha Film Institute, The")

**Comment by NivesKrizanec** [comment]
> Great, thanks for the initial extracted data set @NivesKrizanec - couple of comments:
> 
> * Please, add a markdown readme file with example records of the three files so students get a gist without downloading the entire file. This should also include the reference to the source of the files because we need to give the dataset creators credit (and at least one of the licenses requires it). You'll find examples in the other datasets of this repo.
> * Try to create consistency across all references of countries (e.g., en vs en-English vs FR-France vs tl-)
> * Drop the crew attribute from Movies.csv (please also rename from MovieMetadata) and related persons from Persons.csv. I think the scenario is already complex enough and the characteristics of crew handling are almost identical to cast handling.
> * Rename the attribute CastCreditID to CastIDs
> * Avoid the need for double quoting as a means of escaping strings which contains commas. You can maybe replace these commas with a semicolon (e.g., "France 2 Cinéma|Quinta Communications|Carthago Films S.a.r.l.|Prima TV|Doha Film Institute, The")

@mboehm7 
I have now finished the README as well as fixed the problems within the files.
Regarding the consistency of countries, in the example you gave -  (e.g., en vs en-English vs FR-France vs tl-) - 'en' references the English language and 'FR' is referencing the country France. Whenever a language is abbreviated the ISO 639-1 language code is used, which is by standard a two letter lower case abbreviation for the language, on the other hand, when the abbreviation is referencing a country, the two letter upper case version of the ISO 3199-1 country code is used. Since the two are not related and adhere to their respective standards, I believe they shouldn't be changed, but if I have misunderstood something, I can change it without a problem.

**Comment by mboehm7** [comment]
Thanks for your efforts @NivesKrizanec - I'll have a detailed look into this and merge it Sunday (when I'm back from vacation).

**Comment by mboehm7** [comment]
LGTM - thanks for the additional modifications @NivesKrizanec. Regarding consistency of languages and countries, thanks for the references and I agree that we should stick to these definitions. However, I would appreciate some additional cleanups. First, for the original language we only use the code, while for the list of languages we use codes and names (I would recommend to use the same either code or code-name). Second, some of the code-name pairs seem corrupted. For example, the codes tl, ar, he, me, and yi have a tab instead of the name (maybe due to replacement of special characters).

**Comment by mboehm7** [comment]
And if possible, let's convert the rating timestamps to the same date format as the release date. It smelled like being a unix timestamp (seconds since 1970) but that gave timestamps in 2009 for movies from 2011. So this is a nice-to-have - maybe the original datasets give some more info how the timestamps were generated.

**Comment by NivesKrizanec** [comment]
As requested I added also the language name in the OriginalLanguage column (new format: code-language) as well as added the corresponding language name to all the language codes that were missing it. The language names were missing in the original dataset as well, so I added them manually. Regarding the timestamp of the rating, I visited the original website from where the ratings were taken and in their words the timestamps "represent seconds since midnight Coordinated Universal Time (UTC) of January 1, 1970.".  From my understanding that is the unix timestamp, so I transformed it according to that, but I can change that if needed. Sadly I could not find any information on why the rating dates are so much earlier before the release.
Should I do again a pull request?

**Comment by mboehm7** [comment]
sounds good - yes, please create a second PR so we can introduce the exercise on Monday and link to the data.

**Pull request closed without merging**
