### PR TITLE
First version

### PR DESCRIPTION
**Pull request by NivesKrizanec**
In addition to what was in the email, I went through all NOC codes manually and changed the team names to the official names found on the official webpage - _https://www.olympic.org/ioc-governance-national-olympic-committees_ - and the Wikipedia page - _https://en.wikipedia.org/wiki/List_of_IOC_country_codes#Current_NOCs_. There were cases where multiple NOCs has the same team name e.g. "**Germany**" was used for GER, FRG and GDR, where FRG should be "**East Germany**" and GDR "**West Germany**".

If I have missed any of the requirements, please let me know and I will fix it asap.

Happy Easter Holidays!

### CODE REVIEW

**Comment by mboehm7** [comment]
Thanks @NivesKrizanec for your effort getting the dataset ready. Two quick comments: could you please use the schema 'yyy-mm-dd' for all dates to make it consistent with other datasets in this repo, and for simplification create a single start-end date for the games that happened in two cities (min->begin, max->end). @phaniarnab could you please have a more detailed look and help merge this in?

**Comment by phaniarnab** [comment]
Thanks for your effort @NivesKrizanec. 
In addition to Matthias's comments, I have a few more.
1. Currently two schemas are being used for dates (e.g. 1886-01-01, 1/1/1920). Please use yyyy-mm-dd consistently as suggested by Matthias.
2. Population and GDP are missing for some countries which exist today (e.g. Eritrea, Cuba). You can get these from other sources.
3. The column name 'Team' in the new NOCRegions file seems unnatural (a team doesn't have population and GDP). Please change it to 'Region'.
3. The event names are quite convoluted in the AthleteEvents file. I would like them in the same format as they are in the medals_summary file (e.g. '_Athletics Men's 3;000 metres Steeplechase_' vs '_3000M Steeplechase_'). This format makes it easier to use event names in the WHERE clauses and also doesn't encode the gender and the sport name.
4. Missing heights and weights can be imputed by the average within the same event. However, this may not be necessary right now if they are irrelevant to the queries in exercise 2.

**Comment by NivesKrizanec** [comment]
Regarding the first point, all of the dates seem to be in the yyyy-mm-dd format, when I open it in a regular text editor. On the other hand, I did find that excel does not consistently show all of the dates in this format (some are yyyy-mm-dd and some dd/mm/yyyy ). I've been trying to find the issue but had no luck so far.
Please let me know if this is important to fix (since the raw files show all of the dates correctly), and if there is perhaps a known fix for this issue.
Thank you for your help!

**Comment by phaniarnab** [comment]
> **@phaniarnab**
> Regarding the first point, all of the dates seem to be in the yyyy-mm-dd format, when I open it in a regular text editor. On the other hand, I did find that excel does not consistently show all of the dates in this format (some are yyyy-mm-dd and some dd/mm/yyyy ). I've been trying to find the issue but had no luck so far.
> Please let me know if this is important to fix (since the raw files show all of the dates correctly), and if there is perhaps a known fix for this issue.
> Thank you for your help!

Can you please try to quickly import the csv in PostgreSQL to see if all the dates are in the desired format?

**Comment by mboehm7** [comment]
LGTM - thanks @NivesKrizanec and @phaniarnab. After the latest updates, the dates look fine to me. Also, Artem is working on the reference solution for Exercise 2, which would then anyway reveal remaining issues. Btw, I also like the modified HostCities file with the added NOC code.

**Comment by mboehm7** [comment]
During the merge, I just fixed few minor types, changed the Gender to non-binary, and added an explanation for the absence of medal information.

**Comment by NivesKrizanec** [comment]
@phaniarnab @mboehm7 
Regarding changing the event names, as suggested by Arnab, I do not see a different functioning solution other than finding the "translations" of all unique event names from AthleteEvents in medals_summer by hand and afterwards running the file through the program to make all replacements. This should take a while to finish due to over 500 unique events.
Is there perhaps a more efficient solution I am missing? Additionally, when should the dataset be finalized?

**Comment by mboehm7** [comment]
Thanks for asking @NivesKrizanec, I would recommend to wait until we have the schema sorted out. Once ingested, I would do a few group-by, order-by, extract queries to see if there is a pattern which allows us to extract these lookup tables automatically. Likely, there are simple things that can be done, like replacing the long BE version metres and so on.

**Pull request closed without merging**
