### PR TITLE
Movies dataset

### PR DESCRIPTION
**Pull request by NivesKrizanec**

### CODE REVIEW

**Comment by mboehm7** [comment]
@NivesKrizanec - could you please clone from main, and add only the new commits? Alternatively, you could also resolve the merge conflicts here (note that I changed the readme when I merged your first PR).

**Comment by NivesKrizanec** [comment]
I have now resolved the merge conflicts.

**Comment by mboehm7** [comment]
Thanks @NivesKrizanec - I'm now merging this in. However, there still seem to be some problems with the codes ar, fa, he, ku. Regarding PRs, I would recommend to created a new branch from master for every PR.

**Comment by NivesKrizanec** [comment]
I could not find the problem with these examples. Could you please explain what it is? The only difference regarding these languages I found was that they are written from right to left, which means that in instances where the movie title follows directly after the name of the language, they are displayed "reversed" in a text editor.

**Comment by mboehm7** [comment]
Hmm, I think you're right - apparently it was a character encoding issue in vi. When double check the files, I get
```
Movies.csv: text/plain; charset=utf-8
Ratings.csv: text/plain; charset=us-ascii
Persons.csv: text/plain; charset=utf-8
```
which is fine as us-ascii is a subset of utf-8.

**Pull request closed without merging**
