### PR TITLE
initial data cleaning

### PR DESCRIPTION
**Pull request by NivesKrizanec**
I merged the population by EU-Status and by Nationality into a single file. Also all of the institution data is in one file. One issue I have there is that I am not sure what KAT2 and KAT3 stand for in the original files, therefore i left a question mark in the README file.
I am not sure how to handle the file _Volkszaehlung_nach_Alter.csv_. I can not understand exactly how the data is divided and what means what. It is also from a different time period then the other data. If there is a need for an additional file PopulationByAge I would suggest to use the file at the following link: https://ckan.data.graz.gv.at/daten/package/1780b0e8-297d-40c7-8341-6bba62087c53.

### CODE REVIEW

**Comment by mboehm7** [comment]
LGTM - during the merge I shortened the filename to Institutions.csv. The categories 2 and 3 can be named InstitutionsCategory and InstitutionsType (where the latter is a subtype of the former). Personally, I would have left the streets in a separate file, but it's ok and ensures the 1:N mapping. The institutions are a bit odd and outdated, but that's real data and fine. Any additional changes can be made once we have the first draft of the reference schema, ingestion program, and queries.

**Comment by mboehm7** [comment]
Thanks for the effort @NivesKrizanec

**Comment by NivesKrizanec** [comment]
I need to add a remark that according to the dataset, streets can be located in multiple districts. In the assignment sheet i saw that it is stated a street can only be in one district. If that should be changed (e.g. street should be related to only one of its districts district) please let me know.

**Comment by mboehm7** [comment]
I thought in the original dataset each street had a district ID not multiple - do you have an example of a street that stretches districts?

**Comment by NivesKrizanec** [comment]
Yes, for example (from the raw file): 112;Alte Poststraße;4,5,14,15,16,17;
So the street Alte Poststraße goes through 6 districts, namely Lend, Gries, Eggenberg, Wetzelsdorf, Straßgang and Puntigam.
I think this is the most extreme example, but there are a few other ones that go through 2-3 districts.

**Comment by mboehm7** [comment]
ok thanks - then yes please add a note, or restore the original streets.csv - I think we don't need to unnecessarily complicate it for students. I'll leave it up to you. Thanks @NivesKrizanec

**Pull request closed without merging**
